### ISSUE TITLE
Fanfiction.net Cover not downloading correctly

### ISSUE THREAD

**Issue by MrTyton** [JimmXinu/FanFicFare#177]
Recently, for about the past week~ that I've been noticing, both in CLI and in plugin, FFF hasn't been downloading covers properly from fanfiction.net. In most cases it's been overwriting whatever cover is there with the one created by GenerateCover. This occurs even when I tell it to update metadata only and to download from the site, using the plugin. Occurs both with new stories or with old ones that I'm updating.

I think this is occurring because of [319](https://github.com/JimmXinu/FanFicFare/blob/master/fanficfare/adapters/adapter_fanfictionnet.py#L319). There are stories such as [this](https://www.fanfiction.net/s/12146135/1/) where the authimg_id is the same as the cover_id, but that doesn't mean that there still isn't a picture there. It just doesn't do anything at like 323 then.

Example output:

One where there is a cover on the site, but the things are the same. End result is that it uses the generated cover instead of what's on the site. The only difference between the urls is the last part, 180 vs 150.

> user@Ryouzanpakuto:~$ fanficfare -d -u "The Entertainer - Coeur Al'Aran_2392.epub" --update-cover -m
Updating The Entertainer - Coeur Al'Aran_2392.epub, URL: https://www.fanfiction.net/s/12146135/1/
FFF: DEBUG: 2017-04-27 13:47:37,270: adapter_fanfictionnet.py(98): URL: https://www.fanfiction.net/s/12146135/1/
FFF: DEBUG: 2017-04-27 13:47:37,271: configurable.py(998): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/12146135/1/
FFF: DEBUG: 2017-04-27 13:47:43,091: adapter_fanfictionnet.py(294): cover_url://ffcdn2012t-fictionpressllc.netdna-ssl.com/image/4573878/180/
FFF: DEBUG: 2017-04-27 13:47:43,094: configurable.py(998): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/u/6272865/Coeur-Al-Aran
FFF: DEBUG: 2017-04-27 13:47:49,112: adapter_fanfictionnet.py(307): authimg_url://ffcdn2012t-fictionpressllc.netdna-ssl.com/image/4573878/150/
Do update - epub(23) vs url(23)
FFF: INFO: 2017-04-27 13:47:52,114: base_writer.py(179): Save directly to file: The Entertainer - Coeur Al'Aran_2392.epub
FFF: WARNING: 2017-04-27 13:47:52,115: base_writer.py(195): File(The Entertainer - Coeur Al'Aran_2392.epub) Updated(2017-04-27) more recently than Story(2017-04-25) - Skipping

Cover on the site, but the urls are different, so it uses what it finds on the site. The differences between the urls are the part that's checked, part [4], as well as the 180 vs 150.

> user@Ryouzanpakuto:~$ fanficfare -d -u Heroes\ Assemble\!\ -\ Stargon1_2395.epub --update-cover -m
Updating Heroes Assemble! - Stargon1_2395.epub, URL: https://www.fanfiction.net/s/12307781/1/
FFF: DEBUG: 2017-04-27 13:49:13,551: adapter_fanfictionnet.py(98): URL: https://www.fanfiction.net/s/12307781/1/
FFF: DEBUG: 2017-04-27 13:49:13,552: configurable.py(998): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/12307781/1/
FFF: DEBUG: 2017-04-27 13:49:19,577: configurable.py(998): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/Harry-Potter_and_Avengers_Crossovers/224/9786/
FFF: DEBUG: 2017-04-27 13:49:25,954: adapter_fanfictionnet.py(294): cover_url://ffcdn2012t-fictionpressllc.netdna-ssl.com/image/4391502/180/
FFF: DEBUG: 2017-04-27 13:49:25,957: configurable.py(998): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/u/5643202/Stargon1
FFF: DEBUG: 2017-04-27 13:49:32,684: adapter_fanfictionnet.py(307): authimg_url://ffcdn2012t-fictionpressllc.netdna-ssl.com/image/3060419/150/
Do update - epub(17) vs url(17)
FFF: INFO: 2017-04-27 13:49:34,436: base_writer.py(179): Save directly to file: Heroes Assemble! - Stargon1_2395.epub
FFF: WARNING: 2017-04-27 13:49:34,438: base_writer.py(195): File(Heroes Assemble! - Stargon1_2395.epub) Updated(2017-04-27) more recently than Story(2017-04-26) - Skipping

Though honestly I don't know if that's the root cause: I can't access either of those links (get 403 forbidden) and commenting out lines 320 and 321 didn't seem to change anything, so I'm not sure.

**Comment by MrTyton** [comment]
Honestly it could just be tied to the cover urls now giving 403 errors, and it's only being caught on these stories; if it can't download the cover due then does it just autogenerate the cover?

**Comment by JimmXinu** [comment]
This issue was already fixed in b36f41335a5fedc17149b2d1849d200c5ece5075.  I get the story cover image for both those using the current test version.

> I've posted a test version of the plugin here:
> http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025
>
> Test version of web service here:
> https://2-10-5-dot-fanficfare.appspot.com/
> 
> I've put up a test version for pip install.  You'll have to get it from the testpypi repository.  This works for me on Debian:
> 
> pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare

**Comment by MrTyton** [comment]
Ah, ok. Thanks!

**Comment by MrTyton** [comment]
What is the cause of the issue though, I'm just wondering.

**Comment by JimmXinu** [comment]
The refactoring in 228b94592eec49ebfc7b13fb8082bbfb45ce9181 broke the ffnet specific code that set Referer.  

Because it didn't effect anything except cover image, I didn't notice right away.  b36f41335a5fedc17149b2d1849d200c5ece5075 made it a more general feature for all image fetches.

**Comment by MrTyton** [comment]
It's still not working for me though. I tried both updating an existing epub as well as downloading from scratch, both with the cli from the pip and from the test archive.

**Comment by JimmXinu** [comment]
Turns out I had `skip_author_cover: false` in `personal.ini` from testing something else.  So my bad for reporting that wrongly before.

From what I see (running CLI on Debian using using latest testpypi pip install):

- https://www.fanfiction.net/s/12146135/1/ - correctly trips `skip_author_cover` (when true) and _doesn't_ include the cover because it's the same as the author.

- https://www.fanfiction.net/s/12307781/1/ - correctly _does_ get story cover regardless of `skip_author_cover` setting.

Are you sure you have `include_images:true` in `personal.ini`?  CLI defaults that to false.

**Comment by MrTyton** [comment]
I have include_images:true in personal.ini

What I did not have was skip_author_cover: false, so my test case was bad.
Sorry for the confusion, I've fixed that in my personal.ini

Now I can go and fix all the covers that broke from before!!

Thanks.
